# Generated by Django 5.2.7 on 2025-11-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fee_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('status', models.CharField()),
                ('payment_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='staff_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField()),
                ('department', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('hire_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='student_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=100)),
                ('join_date', models.DateField()),
            ],
        ),
    ]
